version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/TenantCatalog/TenantCatalog/TenantCatalog.Application/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/TenantCatalog/TenantCatalog/TenantCatalog.Domain/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/TenantCatalog/TenantCatalog/TenantCatalog.Events/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/TenantCatalog/TenantCatalog/TenantCatalog.Infrastructure/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/TenantCatalog/TenantCatalog/TenantCatalog.Web.API/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"

  - package-ecosystem: "nuget"
    directory: "/TenantCatalog/TenantCatalog/Tests/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "deps"
      include: "scope"
